Update json-validator.yml

diff --git a/.github/workflows/json-validator.yml b/.github/workflows/json-validator.yml
--- a/.github/workflows/json-validator.yml
+++ b/.github/workflows/json-validator.yml
@@ -19,7 +19,7 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v3
         with:
-          fetch-depth: 0
+          fetch-depth: ${{ github.event_name == 'pull_request' && 2 || 0 }}
 
       - name: Use Node.js
         uses: actions/setup-node@v3
@@ -32,20 +32,22 @@ jobs:
       - name: Validate JSON
         run: |
           echo "Searching for JSON files..."
-          FILE_TO_VALIDATE=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep '\.json$')
+          if [ "${{ github.event_name }}" == "pull_request" ]; then
+            FILE_TO_VALIDATE=$(git diff --name-only HEAD^1 HEAD | grep '\.json$' | head -n 1)
+          else
+            FILE_TO_VALIDATE=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.json$' | head -n 1)
+          fi
           echo "$FILE_TO_VALIDATE"
           if [ -z "$FILE_TO_VALIDATE" ]; then
             echo "No JSON files found for validation."
             exit 0
           fi
           
-          echo "Validating JSON files..."
-          for file in $FILE_TO_VALIDATE; do
-            if [ -f "$file" ]; then
-              echo "Validating $file..."
-              ajv validate -s validationSchema.json -d "$file" || exit 1
-            else
-              echo "$file not found. Skipping..."
-            fi
-          done
+          echo "Validating JSON file..."
+          if [ -f "$FILE_TO_VALIDATE" ]; then
+            echo "Validating $FILE_TO_VALIDATE..."
+            ajv validate -s validationSchema.json -d "$FILE_TO_VALIDATE" || exit 1
+          else
+            echo "$FILE_TO_VALIDATE not found. Skipping..."
+          fi
           echo "Validation complete."
