Modify approval and proposal actions. Same as trig

diff --git a/.github/workflows/proposal-validator.yml b/.github/workflows/proposal-validator.yml
--- a/.github/workflows/proposal-validator.yml
+++ b/.github/workflows/proposal-validator.yml
@@ -1,25 +1,35 @@
-name: Proposal Validator
+name: Validate Proposing application
 
 on:
-  push:
-    branches: [ "main" ]
   pull_request:
-    branches: [ "main" ]
-
-env:
-  CARGO_TERM_COLOR: always
+    types:
+      - opened
+      - synchronize
+  pull_request_review:
+    types:
+      - submitted
 
 jobs:
-  build:
-
+  call-backend:
     runs-on: ubuntu-latest
-
+    env:
+      DOMAIN: ${{ secrets.DOMAIN }}
     steps:
-    - uses: actions/checkout@v3
-    - name: Install fplus-cli
-      run: echo 'Install fplus-cli'
-      # run: cargo install fplus-cli
-    - name: Validate Proposal
-      run: echo 'Validate Proposal'  
-      # run: fplus-cli validate-proposal app_id
+      - name: Call Backend to Validate
+        id: validate
+        run: |
+          echo "Calling backend to validate with pr_number: ${{ github.event.pull_request.number }} and user_handle: ${{ github.actor }}"
+          RESPONSE=$(curl --header "Content-Type: application/json" \
+            --request POST \
+            --data '{"pr_number": "'${{ github.event.pull_request.number }}'", "user_handle": "'${{ github.actor }}'"}' \
+            "${DOMAIN}/application/propose/validate")
+          echo "Response from validation: $RESPONSE"
 
+          if [ "$RESPONSE" != "true" ]; then
+            echo "Error: Validation returned false"
+            exit 1
+          fi
+
+      - name: Validation Success
+        if: steps.validate.outcome == 'success'
+        run: echo "Validation successful!"
